apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.secrets.postgresql.username }}
  password: {{ .Values.secrets.postgresql.password }}
  database: {{ .Values.secrets.postgresql.database }}
---
{{- if .Values.secrets.redis.password }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  password: {{ .Values.secrets.redis.password }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  webhook-url: {{ .Values.secrets.slack.webhookUrl }}
